version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
  - package-ecosystem: gomod
    schedule:
        interval: "daily"
    directory: /
  - package-ecosystem: github-actions
    schedule:
        interval: "weekly"
    directory: /
